### ISSUE TITLE
Ios background advertising not working

### ISSUE THREAD

**Issue by sridharmari** [c19x/C19X-iOS#3]
Dear Team, 

Background bluetooth advertising is not functioning in the background. Kindly help us on it.

**Comment by c19x** [comment]
Hello! Happy to help. Would you mind elaborating on the issue? iOS background advertising is working normally on all my test devices (iPhone X on iOS 13.2 running C19X-iOS, iPhone X on iOS 13.5 running C19X-iOS, iPhone 4S on iOS 9.3 running C19X-iOS-BLE). I've just checked them all.
